version: '3.8'

services:
  # Backend API service
  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: legal_clinic_bot
    restart: always
    env_file:
      - ./.env
    volumes:
      # Mount logs directory to host machine for persistent log storage
      - ./bot/logs:/app/logs
      # Mount i18n directory to host machine for persistent i18n storage
      - ./bot/i18n:/app/i18n:z
    networks:
      - legal_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legal_clinic_backend
    restart: always
    environment:
      - PORT=${BACKEND_PORT}
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${BACKEND_EXPOSE}:${BACKEND_PORT}"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - legal_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_TELEGRAM_BOT_NAME: ${NEXT_PUBLIC_TELEGRAM_BOT_NAME}
    container_name: legal_clinic_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${FRONTEND_EXPOSE}:${FRONTEND_PORT}"
    networks:
      - legal_net

networks:
  legal_net:
    driver: bridge