version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legal_clinic_backend
    restart: always
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:10161:10161"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - legal_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: legal_clinic_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:10162:10162"
    networks:
      - legal_net

networks:
  legal_net:
    driver: bridge