version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legal_clinic_backend
    restart: always
    environment:
      - PORT=${BACKEND_PORT}
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${BACKEND_EXPOSE}:${BACKEND_PORT}"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - legal_net
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_TELEGRAM_BOT_NAME: ${NEXT_PUBLIC_TELEGRAM_BOT_NAME}
        NEXT_PUBLIC_TELEGRAM_BOT_CLIENT_ID: ${NEXT_PUBLIC_TELEGRAM_BOT_CLIENT_ID}
    container_name: legal_clinic_frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:${FRONTEND_EXPOSE}:${FRONTEND_PORT}"
    networks:
      - legal_net
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 128M

networks:
  legal_net:
    driver: bridge